#!/usr/bin/env python3
"""Generate the shared key geometry/UV table; no photograph pixels are edited."""
import json
from pathlib import Path
root=Path(__file__).resolve().parents[1]
left='PXL_20261009_132916421.MP.jpg'
right='PXL_20261009_132919894.jpg'
keys=[]
def key(label,u,row,width=1,style=0,photo=left,cx=None,cy=None,height=1):
    x=-247+u*20.0;y=35-row*20.0
    item=dict(label=label,x=x,y=y,width=width,height=height,style=style)
    if cx is not None:
        # Photos are portrait, with the keyboard turned clockwise. Keep the
        # pixels untouched and rotate the UV coordinates instead.
        dx=43 if height==1 else 95;dy=43*width
        item['photo']=photo
        item['uv']=[[ (cx+dx)/1373,(cy-dy)/1824 ],[(cx+dx)/1373,(cy+dy)/1824],[(cx-dx)/1373,(cy+dy)/1824],[(cx-dx)/1373,(cy-dy)/1824]]
    keys.append(item)
key('ALT',.75,0,1.5,1,cx=870,cy=250)
for i,label in enumerate(['1','2','3','4','5','6','7','8','9','0','ß','^']):
    key(label,2+i,0,cx=872,cy=381+i*120)
key('R',14,0,photo=right,cx=850,cy=420)
key('SI SO',15.5,0,style=1,photo=right,cx=850,cy=590)
key('CTRL',.75,1,1.5,cx=755,cy=276)
for i,label in enumerate('QWERTYUIOP'):
    key(label,2.25+i,1,cx=754,cy=444+i*120)
key('@',12.25,1,cx=754,cy=1644)
key('{',13.25,1,photo=right,cx=735,cy=330)
key('→',14.25,1,photo=right,cx=735,cy=443)
key('INS',15.5,1,style=1,photo=right,cx=735,cy=590)
key('DEL',16.5,1,style=1,photo=right,cx=735,cy=700)
key('•',1,2,cx=641,cy=333)
for i,label in enumerate('ASDFGHJKL'):
    key(label,2.25+i,2,cx=644,cy=455+i*120)
key('+',11.25,2,cx=644,cy=1535)
key('*',12.25,2,cx=644,cy=1655)
key('}',13.25,2,photo=right,cx=619,cy=330)
key('Shift',.75,3,1.5,cx=526,cy=253)
for i,label in enumerate(['|','Z','X','C','V','B','N','M',',','.','?']):
    key(label,2+i,3,cx=526,cy=386+i*120)
key('Shift',13.5,3,1.5,photo=right,cx=505,cy=333)
key('Space',7.5,4,8,cx=413,cy=1010)
key('ET',12.8,4,1.5,photo=right,cx=386,cy=216)
for row in (2,3,4):
    for col in range(3):
        key(['←','↑','→'][col] if row!=4 else ['Return','↓','F15'][col],14.5+col,row,style=1,photo=right,cx=[0,0,620,504,386][row],cy=470+col*117)
for row,labels in enumerate([['PF1','PF2','PF3'],['7','8','9'],['4','5','6'],['1','2','3'],['0','00',',']]):
    for col,label in enumerate(labels):
        key(label,18+col,row,style=int(row==0),photo=right,cx=[845,733,616,503,382][row],cy=895+col*114)
for row,label in enumerate(['PF4','CE','-']):
    key(label,21.5, row,style=1 if row==0 else 2 if row==1 else 0,photo=right,cx=[844,733,618][row],cy=1302)
key('↔',21.5,3.5,height=2,photo=right,cx=442,cy=1302)
for row in range(5):
    for col in range(2):
        key('PF'+str(5+row+5*col),23+col,row,style=1,photo=right,cx=[839,731,616,501,382][row],cy=1528+col*116)
(root/'keyboard-layout.json').write_text(json.dumps(keys,indent=2)+'\n')
lines=['// Generated by tools/configure.py; positions share browser photo UV data.','// [x, y, width in pitches, height in pitches, material group]','keys = [']
lines += ['  '+json.dumps([k['x'],k['y'],k['width'],k['height'],k['style']])+(',' if i<len(keys)-1 else '')+' // '+k['label'] for i,k in enumerate(keys)]
(root/'keyboard-layout.scad').write_text('\n'.join(lines+ ['];'])+'\n')
print(len(keys),'photo-mapped keys')
